FROM python:3.10-slim as dependency_stage

WORKDIR /code
ENV PATH="/env/bin:$PATH"
RUN python3 -m venv /env

COPY ./requirements.txt /code/requirements.txt

ARG GITLAB_USERNAME
ARG GITLAB_PASSWORD

# echo "machine gitlab.<foo-bar>.de login $GITLAB_USERNAME password $GITLAB_PASSWORD" > ~/.netrc \
# --extra-index-url https://gitlab.<foo-bar>.de/<some-where>/-/packages/pypi/simple
RUN pip install -r /code/requirements.txt
#  && rm -v "$HOME/.netrc"

FROM python:3.10-slim as production_stage
WORKDIR /code
ENV PATH="$WORKDIR/env/bin:$PATH"
COPY --from=dependency_stage /env /env
ENV CONFIG_DIR=/VOLUME_MOUNTS_docker_compose_dir/system-config/service-a
ENV VOLUME_MOUNTS_some_prefix_key=/VOLUME_MOUNTS_some_prefix_key
ENV SOME_CACHE=/cache
COPY --from=some-prefix-just-for-testing/volume-provider_some_prefix_key-some_type_of_resource-some_resource:27-May-07-53-48-229538 /volume-data_some_prefix_key-some_type_of_resource-some_resource /VOLUME_MOUNTS_some_prefix_key/some_type_of_resource/some_resource
COPY --from=some-prefix-just-for-testing/volume-provider_some_prefix_key-dc_systems_cache-mlservicestandalonedocker-service-a-standalone339b3c7a9f5d395c9f41baa3578ae36974f89afd:27-May-07-53-48-229538 /volume-data_some_prefix_key-dc_systems_cache-mlservicestandalonedocker-service-a-standalone339b3c7a9f5d395c9f41baa3578ae36974f89afd /VOLUME_MOUNTS_docker_compose_dir/system-config

# TODO: maybe somewhen in future one could want a prepare stage?
# COPY some_service.py /code/tests/fastapi_service_for_testing/some_service.py
# COPY prepare_service.py /code/prepare_service.py
# RUN python /code/prepare_service.py
# TODO: prepare and production stage are essentially one! otherwise I would have to copy everything twice
#COPY --from=prepare_stage /cache /cache


COPY ./app /code/app
ENV CONFIG_DIR=/VOLUME_MOUNTS_docker_compose_dir/system-config/service-a
ENV VOLUME_MOUNTS_some_prefix_key=/VOLUME_MOUNTS_some_prefix_key
ENV SOME_CACHE=/cache
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8989"]
